"""Add missing user columns

Revision ID: 2051cdc4878d
Revises: c011544a9d8d
Create Date: 2026-03-11 10:28:17.772217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2051cdc4878d'
down_revision = 'c011544a9d8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('evc_number', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('edahab_number', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('pin', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('pin')
        batch_op.drop_column('edahab_number')
        batch_op.drop_column('evc_number')

    op.drop_table('expenses')
    # ### end Alembic commands ###
