"""Add OTP fields to User

Revision ID: 3eab8f2a7abe
Revises: 78b746f10c70
Create Date: 2026-03-08 11:50:46.622953

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3eab8f2a7abe'
down_revision = '78b746f10c70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reset_otp', sa.String(length=6), nullable=True))
        batch_op.add_column(sa.Column('reset_otp_expiry', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('reset_otp_expiry')
        batch_op.drop_column('reset_otp')

    # ### end Alembic commands ###
