"""Add image to Category

Revision ID: 93939fbd4a75
Revises: 3eab8f2a7abe
Create Date: 2026-03-08 12:36:41.926882

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93939fbd4a75'
down_revision = '3eab8f2a7abe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_column('image')

    # ### end Alembic commands ###
